# Generated by Django 5.1.4 on 2024-12-29 10:52

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Nmae')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Nmae')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('backend', 'BackEnd'), ('frotend', 'FrontEnd'), ('admin', 'Admin'), ('premium', 'Premium'), ('user', 'User')], default='user', max_length=30, verbose_name='User Type')),
                ('is_active', models.BooleanField(default=False, verbose_name='Being Active')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Being Premium')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Being Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Being Superuser')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PremiumSubscription_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانوم'), ('other', 'نمی گویم')], default='other', max_length=30, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to, verbose_name='Profile Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
