# Generated by Django 5.1.4 on 2025-01-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('backend', 'BackEnd'), ('frontend', 'FrontEnd'), ('admin', 'Admin'), ('premium', 'Premium'), ('user', 'User')], default='user', max_length=30, verbose_name='User Type'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_subscription', to='users.premiumsubscription', verbose_name='Subscription')),
            ],
        ),
    ]
