# Generated by Django 5.1.4 on 2025-01-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_premiumsubscription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='premiumsubscription',
            options={'verbose_name': 'PremiumSubscription', 'verbose_name_plural': 'PremiumSubscriptions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
    ]
