# Generated by Django 5.1.4 on 2025-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription'], name='users_payme_subscri_0849b8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='users_payme_payment_0485c0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='users_payme_payment_e0854e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='users_payme_payment_ae0757_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumsubscription',
            index=models.Index(fields=['user'], name='users_premi_user_id_ed367b_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumsubscription',
            index=models.Index(fields=['start_date'], name='users_premi_start_d_f414cc_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumsubscription',
            index=models.Index(fields=['end_date'], name='users_premi_end_dat_0064cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='users_userp_user_id_d181df_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone'], name='users_userp_phone_ed0c08_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender'], name='users_userp_gender_945cf0_idx'),
        ),
    ]
