# Generated by Django 5.1.4 on 2024-12-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gallery_gallery', to='main.product', verbose_name='Product'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='main_catego_categor_1f8dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='main_catego_parent__a9ff92_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='main_catego_slug_f935f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product'], name='main_produc_product_516843_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='main_produc_categor_9c4415_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='main_produc_slug_354b31_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='main_produc_price_98d31c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='main_produc_is_acti_723717_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['willing_exchange'], name='main_produc_willing_2b91cf_idx'),
        ),
    ]
